-- LANGUAGE
INSERT INTO LANGUAGE (NAME, CULTURE)
VALUES ('POLISH', 'pl-PL')

-- EVENT
INSERT INTO EVENT (NAME)
VALUES ('ALL')

INSERT INTO EVENT (NAME)
VALUES ('Culture')

INSERT INTO EVENT (NAME)
VALUES ('Sport')

INSERT INTO EVENT (NAME)
VALUES ('Tourism')

-- OBJECTLOCATION
INSERT INTO OBJECTLOCATION (NAME)
VALUES('All')

INSERT INTO OBJECTLOCATION (NAME)
VALUES('Shops')

INSERT INTO OBJECTLOCATION (NAME)
VALUES('Restaurant')

INSERT INTO OBJECTLOCATION (NAME)
VALUES('Health')

INSERT INTO OBJECTLOCATION (NAME)
VALUES('Education')

INSERT INTO OBJECTLOCATION (NAME)
VALUES('Accommodation')

INSERT INTO OBJECTLOCATION (NAME)
VALUES('Sport')

INSERT INTO OBJECTLOCATION (NAME)
VALUES('Monuments')

--DATATYPE

-- ADDRESS
INSERT INTO DESCR (MAINDESCRID, DESCRIPTION, LANGUAGEID) VALUES (0, 'Adres', 1)
INSERT INTO DATATYPE (NAME, IDDESCR) VALUES ('ADDRESS', 1)
-- DATEEVENT
INSERT INTO DESCR (MAINDESCRID, DESCRIPTION, LANGUAGEID) VALUES (0, 'Data wydarzenia', 1)
INSERT INTO DATATYPE (NAME, IDDESCR) VALUES ('DATEEVENT', 2)
-- ADDITIONALDETAILS
INSERT INTO DESCR (MAINDESCRID, DESCRIPTION, LANGUAGEID) VALUES (0, 'Dodatkowe informacje o wydarzeniu', 1)
INSERT INTO DATATYPE (NAME, IDDESCR) VALUES ('ADDITIONALDETAILS', 3)
-- PRICE
INSERT INTO DESCR (MAINDESCRID, DESCRIPTION, LANGUAGEID) VALUES (0, 'CENA WSTĘPU', 1)
INSERT INTO DATATYPE (NAME, IDDESCR) VALUES ('PRICE', 4)
-- LONG DESCRIPTION
INSERT INTO DESCR (MAINDESCRID, DESCRIPTION, LANGUAGEID) VALUES (0, 'Długi opis', 1)
INSERT INTO DATATYPE (NAME, IDDESCR) VALUES ('LONGDESCRIPTION', 5)
--TITLEABOUT
INSERT INTO DESCR (MAINDESCRID, DESCRIPTION, LANGUAGEID) VALUES (0, 'NAZWA OSRÓDKA KULTURY', 1)
INSERT INTO DATATYPE (NAME, IDDESCR) VALUES ('TITLEABOUT', 6)
--LOCATIONABOUT
INSERT INTO DESCR (MAINDESCRID, DESCRIPTION, LANGUAGEID) VALUES (0, 'LOKALIZACJA OŚRODKA KULTURY', 1)
INSERT INTO DATATYPE (NAME, IDDESCR) VALUES ('LOCATIONABOUT', 7)
--OPENCLOSEHOURSABOUT
INSERT INTO DESCR (MAINDESCRID, DESCRIPTION, LANGUAGEID) VALUES (0, 'GODZINY OTWARCIA OŚRODKA KULTURY', 1)
INSERT INTO DATATYPE (NAME, IDDESCR) VALUES ('OPENCLOSEHOURSABOUT', 8)
--PHONENUMBERABOUT
INSERT INTO DESCR (MAINDESCRID, DESCRIPTION, LANGUAGEID) VALUES (0, 'TELEFON KONTAKTOWY OŚRODKA KULTURY', 1)
INSERT INTO DATATYPE (NAME, IDDESCR) VALUES ('PHONENUMBERABOUT', 9)
--EMAILABOUT
INSERT INTO DESCR (MAINDESCRID, DESCRIPTION, LANGUAGEID) VALUES (0, 'ADRES EMAIL OŚRODKA KULTURY', 1)
INSERT INTO DATATYPE (NAME, IDDESCR) VALUES ('EMAILABOUT', 10)
--LONGDESCRIPTIONABOUT
INSERT INTO DESCR (MAINDESCRID, DESCRIPTION, LANGUAGEID) VALUES (0, 'OPIS SIEWIERZA', 1)
INSERT INTO DATATYPE (NAME, IDDESCR) VALUES ('LONGDESCRIPTIONABOUT', 11)

--OPENCLOSEHOURSLOCATION
INSERT INTO DESCR (MAINDESCRID, DESCRIPTION, LANGUAGEID) VALUES (0, 'GODZINY OTWARCIA LOKALIZACJI', 1)
INSERT INTO DATATYPE (NAME, IDDESCR) VALUES ('OPENCLOSEHOURSLOCATION', 12)
--PHONENUMBERLOCATION
INSERT INTO DESCR (MAINDESCRID, DESCRIPTION, LANGUAGEID) VALUES (0, 'TELEFON KONTAKTOWY LOKALIZACJI', 1)
INSERT INTO DATATYPE (NAME, IDDESCR) VALUES ('PHONENUMBERLOCATION', 13)
--LATITUDE
INSERT INTO DESCR (MAINDESCRID, DESCRIPTION, LANGUAGEID) VALUES (0, 'SZEROKOŚĆ GEOGRAFICZNA', 1)
INSERT INTO DATATYPE (NAME, IDDESCR) VALUES ('LATITUDE', 14)
--LONGTITUDE
INSERT INTO DESCR (MAINDESCRID, DESCRIPTION, LANGUAGEID) VALUES (0, 'WYSOKOŚĆ GEOGRAFICZNA', 1)
INSERT INTO DATATYPE (NAME, IDDESCR) VALUES ('LONGTITUDE', 15)

