
--TEST_DATA

-- NEWS
BEGIN 

-- KONCERT DODY
INSERT INTO NEWS (TITLE, CREATEDDATE, EVENTID)
VALUES ('Koncert Wielkanocny Dody', GETDATE(), 3)

DECLARE @IDNEWS INT = (SELECT MAX(NEWSID) FROM NEWS);
INSERT INTO NEWSDATA (NEWSID, DATATYPEID, VALUE)
VALUES (@IDNEWS, 1, 'Porębska 11')
INSERT INTO NEWSDATA (NEWSID, DATATYPEID, VALUE)
VALUES (@IDNEWS, 2, '22-11-2021 18:00')
INSERT INTO NEWSDATA (NEWSID, DATATYPEID, VALUE)
VALUES (@IDNEWS, 3, 'Impreza od lat 12')
INSERT INTO NEWSDATA (NEWSID, DATATYPEID, VALUE)
VALUES (@IDNEWS, 3, 'Dzieci pod opieką dorosłego')
INSERT INTO NEWSDATA (NEWSID, DATATYPEID, VALUE)
VALUES (@IDNEWS, 4, '20zł')

-- WYSTAWA LEGO
INSERT INTO NEWS (TITLE, CREATEDDATE, EVENTID)
VALUES ('Wystawa lego', GETDATE(), 4)

SET @IDNEWS = (SELECT MAX(NEWSID) FROM NEWS);
INSERT INTO NEWSDATA (NEWSID, DATATYPEID, VALUE)
VALUES (@IDNEWS, 1, 'Porębska 11')

INSERT INTO NEWSDATA (NEWSID, DATATYPEID, VALUE)
VALUES (@IDNEWS, 2, '22-12-2022 18:00')

INSERT INTO NEWSDATA (NEWSID, DATATYPEID, VALUE)
VALUES (@IDNEWS, 4, 'BEZPŁATNE')

-- FEEL
INSERT INTO NEWS (TITLE, CREATEDDATE, EVENTID)
VALUES ('Feel - Poczuj zew Anioła', GETDATE(), 2)


SET @IDNEWS = (SELECT MAX(NEWSID) FROM NEWS);

INSERT INTO NEWSDATA (NEWSID, DATATYPEID, VALUE)
VALUES (@IDNEWS, 1, 'GLADIATORA 31')
INSERT INTO NEWSDATA (NEWSID, DATATYPEID, VALUE)
VALUES (@IDNEWS, 4, '600ZŁ')
INSERT INTO NEWSDATA (NEWSID, DATATYPEID, VALUE)
VALUES (@IDNEWS, 2, '22-01-2022 18:00')


-- MECZ B-KLASY

INSERT INTO NEWS (TITLE, CREATEDDATE, EVENTID)
VALUES ('Hitowy mecz b-klasy', GETDATE(), 3)

SET @IDNEWS = (SELECT MAX(NEWSID) FROM NEWS);

INSERT INTO NEWSDATA (NEWSID, DATATYPEID, VALUE)
VALUES (@IDNEWS, 1, 'SPORTOWA 1')
INSERT INTO NEWSDATA (NEWSID, DATATYPEID, VALUE)
VALUES (@IDNEWS, 2, '18-04-2022 20:45')

END


-- DATA

INSERT INTO DATA (DATATYPEID, VALUE)
VALUES(6, 'Miejski ośrodek kultury Siewierz')
INSERT INTO DATA (DATATYPEID, VALUE)
VALUES(7, 'ul. Słowackiego 2a\n42-470 Siewierz')
INSERT INTO DATA (DATATYPEID, VALUE)
VALUES(8, 'Dni Tygodnia - 8:30 - 18:00 \nDni wolne - 8:30 - 19:00')
INSERT INTO DATA (DATATYPEID, VALUE)
VALUES(9, '32 67 41 649')
INSERT INTO DATA (DATATYPEID, VALUE)
VALUES(10, 'mgcksit@siewierz.pl')
INSERT INTO DATA (DATATYPEID, VALUE)
VALUES(11, 'Siewierz należy do najstarszych grodów w Polsce, jednakże jego początki nie są znane, bowiem nie zachowały się dawne dokumenty, zaś dotąd nie przeprowadzono odpowiednich badań archeologicznych. Pierwsza wzmianka historyczna znajduje się w dokumencie legata papieskiego Idziego z 1125 r. w którym napisano, iż klasztor Benedyktów w Tyńcu pod Krakowem pobierał część opłat z targu i jatki w Siewierzu. Dalszym dowodem istnienia grodu oraz jego funkcji w handlu śląsko-małopolskim jest fakt działalności komory celnej w Siewierzu, z której dochody pobierał konwent norbertanek z Rybnika w 1233 r. W początkach swego istnienia Siewierz wchodził w skład kasztelanii bytomskiej w granicach ziemi krakowskiej. W 1177 r. Kazimierz Sprawiedliwy podarował Bytom, Oświęcim i Siewierz Mieszkowi Plątonogiemu, księciu raciborskiemu. W początkach XIII w. Siewierz był już siedzibą kasztelami, bowiem stare śląskie dokumenty wymieniają nazwiska pierwszych kasztelanów: Jaksę i Wawrzyńca. Gród siewierski w tym czasie położony był wokół kościoła św. Jana Chrzciciela, a więc na terenie obecnego cmentarza grzebalnego. Prawdopodobnie w 1241 r. po spaleniu grodu przez Tatarów przeniesiono osadę w dolinę Czarnej Przemszy chronioną rzeką i rozległymi bagnami. W 1276 r, Siewierz otrzymał prawa miejskie, jednakże nie zachował się dokument lokacyjny. W czasie rozbicia dzielnicowego Siewierz był miejscem znanych bitew. W 1289 r. wojska Władysława Łokietka rozbiły wojska książąt śląskich w walce o tron krakowski , a w 1292 r. Wacław II czeski zwyciężył wojska polskie i zajął Kraków. Odrębność terytorialną ziemi siewierskiej po raz pierwszy stwierdzono w dokumencie z 1266 r., wspominającym o districtus severiensis.')

--LOCATION
BEGIN

-- Park Miejski
INSERT INTO LOCATION(NAME, OBJECTLOCATIONID, ADDRESS)
VALUES ('Park Miejski', 4, 'Żwirki i Wigury 26, 42-470 Siewierz')

DECLARE @IDLOCATIONDATA INT = (SELECT MAX(LOCATIONID) FROM LOCATION);
INSERT INTO LOCATIONDATA(LOCATIONID, DATATYPEID, VALUE)
VALUES (@IDLOCATIONDATA, 14, '50.475273471298564')
INSERT INTO LOCATIONDATA(LOCATIONID, DATATYPEID, VALUE)
VALUES (@IDLOCATIONDATA, 15, '19.2369778461592')
INSERT INTO LOCATIONDATA(LOCATIONID, DATATYPEID, VALUE)
VALUES (@IDLOCATIONDATA, 13, '881-431-121')
INSERT INTO LOCATIONDATA(LOCATIONID, DATATYPEID, VALUE)
VALUES (@IDLOCATIONDATA, 12, 'Pon- Piątek - 8:00 - 16:00, \nsob - ndz 7:00 - 15:00')

-- Plac Zabaw
INSERT INTO LOCATION(NAME, OBJECTLOCATIONID, ADDRESS)
VALUES ('Plac Zabaw', 7, 'Stolarska 2, 42-470 Siewierz')

SET @IDLOCATIONDATA = (SELECT MAX(LOCATIONID) FROM LOCATION);
INSERT INTO LOCATIONDATA(LOCATIONID, DATATYPEID, VALUE)
VALUES (@IDLOCATIONDATA, 14, '50.47534741185839')
INSERT INTO LOCATIONDATA(LOCATIONID, DATATYPEID, VALUE)
VALUES (@IDLOCATIONDATA, 15, '19.23514549951801')
INSERT INTO LOCATIONDATA(LOCATIONID, DATATYPEID, VALUE)
VALUES (@IDLOCATIONDATA, 13, '881-431-121')
INSERT INTO LOCATIONDATA(LOCATIONID, DATATYPEID, VALUE)
VALUES (@IDLOCATIONDATA, 12, '8:00 - 16:00')

INSERT INTO LOCATION(NAME, OBJECTLOCATIONID, ADDRESS)
VALUES ('Plac Zabaw', 7, 'Stolarska 2, 42-470 Siewierz')

--Hotel Natura Residence

INSERT INTO LOCATION(NAME, OBJECTLOCATIONID, ADDRESS)
VALUES ('Hotel Natura Residence', 6, 'Stolarska 2, 42-470 Siewierz')
SET @IDLOCATIONDATA = (SELECT MAX(LOCATIONID) FROM LOCATION);
INSERT INTO LOCATIONDATA(LOCATIONID, DATATYPEID, VALUE)
VALUES (@IDLOCATIONDATA, 14, '50.46622341947345')
INSERT INTO LOCATIONDATA(LOCATIONID, DATATYPEID, VALUE)
VALUES (@IDLOCATIONDATA, 15, '19.202231609038382')
INSERT INTO LOCATIONDATA(LOCATIONID, DATATYPEID, VALUE)
VALUES (@IDLOCATIONDATA, 13, '881-431-121')
INSERT INTO LOCATIONDATA(LOCATIONID, DATATYPEID, VALUE)
VALUES (@IDLOCATIONDATA, 12, '8:00 - 17:00')

--Ruiny Zamku w Siewierzu

INSERT INTO LOCATION(NAME, OBJECTLOCATIONID, ADDRESS)
VALUES ('Ruiny Zamku w Siewierzu', 8, 'Tadeusza Kościuszki, 42-470 Siewierz')
SET @IDLOCATIONDATA = (SELECT MAX(LOCATIONID) FROM LOCATION);
INSERT INTO LOCATIONDATA(LOCATIONID, DATATYPEID, VALUE)
VALUES (@IDLOCATIONDATA, 14, '50.46747274085934')
INSERT INTO LOCATIONDATA(LOCATIONID, DATATYPEID, VALUE)
VALUES (@IDLOCATIONDATA, 15, '19.241545498722413')
INSERT INTO LOCATIONDATA(LOCATIONID, DATATYPEID, VALUE)
VALUES (@IDLOCATIONDATA, 13, '881-431-121')
INSERT INTO LOCATIONDATA(LOCATIONID, DATATYPEID, VALUE)
VALUES (@IDLOCATIONDATA, 12, '10:00 - 18:00')

END

